### PR TITLE
Issue30: Test performance of Conditional Mutations

### PR DESCRIPTION
**Pull request by elinaawise**

### CODE REVIEW

**Comment by elinaawise** [comment]
To simplify the data being reported, I commented out all reporting except the average rate values.

**Comment by ctubbsii** [comment]
Please consider changing the title of this PR to be more descriptive about what it intends to do. Also please consider adding a description. Doing so will give context for any reviewers.

**Comment by Manno15** [comment]
There appears to be some comments that need to be deleted but beyond that it appears to be ready to be merged. Thoughts @ctubbsii @keith-turner ?

**Comment by ctubbsii** [comment]
> There appears to be some comments that need to be deleted but beyond that it appears to be ready to be merged. Thoughts @ctubbsii @keith-turner ?

Yes, deleting the commented out code and/or dead code would be a nice cleanup before merging. Could merge as-is, if you wanted to do that follow-on, @Manno15

**Comment by Manno15** [comment]
Doing it as a follow-on would probably be easier on my end but I am okay with whichever you prefer.

**Comment by ctubbsii** [comment]
Merged. Thanks, @elinaawise ; @Manno15 , feel free to perform any follow-on work in a separate PR to clean up/improve as you see fit.

**Pull request merged**
