### PR TITLE
Update license headers to match main accumulo project

### PR DESCRIPTION
**Pull request by DomGarguilo**
Similiar to https://github.com/apache/accumulo/pull/2774. Copied and edited the description of that PR:

* Update license header template to use https (this has been discussed
  at length on the legal mailing list and elsewhere, and is an
  acceptable URL to reference the license text that the rat plugin has
  been made to support)
* Update to rat 0.15
* Find other uses of http and replace with https unless it breaks a link
  or is a namespace identifier or other situation where http is required
* Use the standardized format of the license header text for the
  markdown files

https://github.com/apache/accumulo/pull/2774 standardized the headers in the .gitignore files however there are no headers in those files in accumulo-testing. Not sure if they should be added here or if they should be left alone.

### CODE REVIEW

**Comment by DomGarguilo** [comment]
> @DomGarguilo I don't think I can review a changeset like this, with 358 files changed. I suspect most of these are automatic changes generated from a base configuration change. if you can separate out the configuration change that caused all the files to be changed, I'll review that, and then you can just add a separate commit that does only the automatic changes generated from the reviewed changes.

Sounds good, I'll try to do that.

**Comment by ctubbsii** [comment]
> Sounds good, I'll try to do that.

No worries. I did it in #244. After that, and the subsequent commit is merged, we can pick up the remaining that you may have caught here, that weren't part of headers.

**Comment by DomGarguilo** [comment]
> > Sounds good, I'll try to do that.
> 
> No worries. I did it in #244. After that, and the subsequent commit is merged, we can pick up the remaining that you may have caught here, that weren't part of headers.

Are you planning to merge the subsequent commit containing the automatically applied headers or should I do that?

**Comment by ctubbsii** [comment]
> Are you planning to merge the subsequent commit containing the automatically applied headers or should I do that?

I've got it. I am done now. If there's anything else remaining in this PR that needs to be done, this can be rebased onto the new main. Otherwise, this can be closed if there's nothing left to do here.

**Comment by DomGarguilo** [comment]
Looks like all my changes were included in commits already merged into main. Closing this as already completed

**Pull request closed without merging**
