### PR TITLE
Replace map reduce prop in continuous ingest verify

### LINKED ISSUE #274: mapred.map.tasks.speculative.execution is deprecated. Instead, use mapreduce.map.speculative
`INFO Configuration.deprecation: mapred.map.tasks.speculative.execution is deprecated. Instead, use mapreduce.map.speculative` gets logged when I run `cingest verify`.

This is set here:
https://github.com/apache/accumulo-testing/blob/ce95056c57d3eff61400486b4a9da8fd73dbe67e/src/main/java/org/apache/accumulo/testing/continuous/ContinuousVerify.java#L193

It should be determined if the suggested replacement will work the way we expect and if it does, replace the deprecated field.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #274

### CODE REVIEW

**Review by dlmarion — APPROVED** [review]
This property name looks correct for the version of Hadoop

**Comment by ctubbsii** [comment]
When was this property changed in Hadoop? We need to be careful we're not breaking things with the earliest Hadoop version we still support.

**Comment by DomGarguilo** [comment]
> When was this property changed in Hadoop? We need to be careful we're not breaking things with the earliest Hadoop version we still support.

Honestly I'm not sure. I am having trouble finding what version this change happened in. I do see that the following code was from 13 years ago at which point this property was already deprecated.

https://github.com/apache/hadoop/blame/833da65d8629e0bdd79097ed26033add9fc1864f/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/util/ConfigUtil.java#L325

**Comment by ctubbsii** [comment]
`git tag --contains 833da65d8629e0bdd79097ed26033add9fc1864f` shows that it appears in at least Hadoop 3.0.0 and newer, and we don't support anything older than that anymore, so this should be good.

**Review by ctubbsii — APPROVED** [review]

**Pull request merged**
