### PR TITLE
Bump maven to 3.8.8 in terraform config

### LINKED ISSUE #263: Terraform setup fails due to old maven version
When running the terraform setup, it got to the step where maven was attempted to be downloaded. A 404 was thrown since the current version default "3.8.6" does not have a binary at the link it was looking for anymore.

Suggested fix:
update the default maven version to pull "3.8.8"

```
module.configure_nodes.null_resource.configure_manager_node (remote-exec): --2023-06-28 16:05:22--  https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
module.configure_nodes.null_resource.configure_manager_node (remote-exec): Resolving [dlcdn.apache.org](http://dlcdn.apache.org/) ([dlcdn.apache.org](http://dlcdn.apache.org/))... 151.101.2.132, 2a04:4e42::644
module.configure_nodes.null_resource.configure_manager_node (remote-exec): Connecting to [dlcdn.apache.org](http://dlcdn.apache.org/) ([dlcdn.apache.org](http://dlcdn.apache.org/))|151.101.2.132|:443... connected.
module.configure_nodes.null_resource.configure_manager_node (remote-exec): HTTP request sent, awaiting response... 404 Not Found
module.configure_nodes.null_resource.configure_manager_node (remote-exec): 2023-06-28 16:05:22 ERROR 404: Not Found.
```

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #263

### CODE REVIEW

**Review by ctubbsii — APPROVED** [review]
This is fine, but I wonder if it would be better to just have the instance do a `yum install` or `apt-get install` the version of Maven that ships with the OS of the base image, so we don't have to keep updating this. Maven is pretty stable from version to version, so it really doesn't matter which version we use, as long as it's relatively recent. We define the plugin versions we care about ourselves.

**Comment by DomGarguilo** [comment]
> This is fine, but I wonder if it would be better to just have the instance do a `yum install` or `apt-get install` the version of Maven that ships with the OS of the base image, so we don't have to keep updating this. Maven is pretty stable from version to version, so it really doesn't matter which version we use, as long as it's relatively recent. We define the plugin versions we care about ourselves.

Seems like a good idea to me. I wonder if that would make it any harder to install a specific version of maven. I guess we might want to still have it as an option to pin a certain version for testing but again, not sure.

**Comment by DomGarguilo** [comment]
Going to merge this for now. Making the change mentioned above can be handled in a separate ticket.

**Comment by dlmarion** [comment]
> This is fine, but I wonder if it would be better to just have the instance do a yum install or apt-get install the version of Maven that ships with the OS of the base image, so we don't have to keep updating this.

I think the only issue with this is that I think the Maven version for CentOS7 is really old, and CentOS7 is still widely used. I think it might be version 3.0.5.

**Comment by ctubbsii** [comment]
I don't think we need to still be supporting CentOS 7 for our testing repo's main branch (accumulo &gt;= 3.0). The terraform scripts can be updated to use something newer, if they aren't already.

**Pull request merged**
