### PR TITLE
Add group commit performance test

### PR DESCRIPTION
**Pull request by keith-turner**
<details>
<summary>Below is example output from running the test in VM on my laptop.</summary>

```json
{
  "testClass": "org.apache.accumulo.testing.performance.tests.GroupCommitPT",
  "accumuloVersion": "2.0.0",
  "startTime": "2020-09-26T01:21:32.982510Z",
  "finishTime": "2020-09-26T01:26:48.936093Z",
  "id": "mutslam",
  "description": "Data written to Accumulo is appended to a write ahead log before its made available for scan.  There is a single write ahead log per tablet server.  Data from multiple concurrent clients is batched together and appended to the write ahead log, this is called group commit.  If group commit is not working properly, then performance of concurrent writes could suffer.  This performance test measures group commit.  In an Accumulo client, when the batch writer is flushed this forces an append to the write ahead log.  The batch writer flush call does not return until the append is complete. This test writes the same amount of data using different numbers of threads to check if group commit is working properly.  When the test is using one thread it will write 2048K total mutations calling flush on the batchwriter 1024 times.  When the test is running two threads, each thread will write 1024K mutations calling flush 1024 times.  The pattern is that as the number of threads increases, the amount of data written per thread decreases proportionally.  However the number of flushes done by threads is constant.  If group commit is working well, then the overall write rate should not be significantly less as the number of threads increases.",
  "results": [
    {
      "id": "warmup_rate_1",
      "data": 85524.73390155377,
      "description": "The warmup rate at which 1 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_2",
      "data": 106932.08239853152,
      "description": "The warmup rate at which 2 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_4",
      "data": 134743.7676689797,
      "description": "The warmup rate at which 4 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_8",
      "data": 97225.40565600371,
      "description": "The warmup rate at which 8 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_16",
      "data": 113286.08470181504,
      "description": "The warmup rate at which 16 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_32",
      "data": 84716.29973742679,
      "description": "The warmup rate at which 32 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_64",
      "data": 53560.26050312859,
      "description": "The warmup rate at which 64 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "rate_1",
      "data": 106584.26509453142,
      "description": "The rate at which 1 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_2",
      "data": 122590.28467878647,
      "description": "The rate at which 2 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_4",
      "data": 135808.31498510556,
      "description": "The rate at which 4 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_8",
      "data": 152033.63781354213,
      "description": "The rate at which 8 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_16",
      "data": 154213.69218324876,
      "description": "The rate at which 16 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_32",
      "data": 95672.99270072993,
      "description": "The rate at which 32 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_64",
      "data": 74478.0169046097,
      "description": "The rate at which 64 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    }
  ],
  "parameters": [
    {
      "id": "num_mutations",
      "data": "2097152",
      "description": "The total number of mutations each test will write.  Each thread in a test will write num_mutations/num_threads_in_test mutations."
    },
    {
      "id": "num_flushes",
      "data": "1024",
      "description": "The number of times each thread will flush its batch writer.  The flushes are spread evenly between mutations."
    }
  ]
}
```

</details>

### CODE REVIEW

**Comment by Manno15** [comment]
From a quick read through, this looks good. I can take a deeper look at this Monday if needed.

**Comment by keith-turner** [comment]
I ran into problems w/ #126 and #127 while working on this.  Not sure what is going on w/ #127 I worked around it by making it always setup up everything from scratch by just running `uno setup accumulo`

**Comment by ctubbsii** [comment]
@keith-turner What command do I run to run this specific test? (assuming I have Uno set up and the cluster-control script written properly). I want to help troubleshoot #127

**Comment by Manno15** [comment]
I ran the test with `./bin/performance run results org.apache.accumulo.testing.performance.tests.GroupCommitPT
` where results in the directory the report gets written too.

**Comment by keith-turner** [comment]
Could also do `./bin/performance run results GroupCommitPT`.  Looking at the code I think the substring works because of the following line.

https://github.com/apache/accumulo-testing/blob/6e2495f117449203086bd2d2bfdbfcc66580aa06/bin/performance#L84

However the following earlier line does not do substring matching on `$3`, but it didn't prevent me from using only the class name.  Not sure why.

https://github.com/apache/accumulo-testing/blob/6e2495f117449203086bd2d2bfdbfcc66580aa06/bin/performance#L72

**Comment by keith-turner** [comment]
@ctubbsii this [section](https://github.com/apache/accumulo-testing#performance-test) of the readme attempts to document the intended purpose of the cluster control functions.

**Comment by keith-turner** [comment]
Looking at the scripts I realized that the way I hacked the cluster control script to make things work probably overwrote the config set by the test.  So the numbers I posted likely do not reflect the config changes the test emitted to set the tserver threads to 128.

**Comment by ctubbsii** [comment]
@keith-turner and @Manno15 Thanks for the info about how to pass the test class to the `performance run` command. That's the piece I was missing from the README.md

**Comment by Manno15** [comment]
I forgot to comment this earlier in the week but I ran through this pull request and everything seemed to work correctly. My results are below:

```
"results": [
    {
      "id": "warmup_rate_1",
      "data": 64543.641511756745,
      "description": "The warmup rate at which 1 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_2",
      "data": 64977.59876065066,
      "description": "The warmup rate at which 2 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_4",
      "data": 67645.70027740145,
      "description": "The warmup rate at which 4 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_8",
      "data": 73924.07205047764,
      "description": "The warmup rate at which 8 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_16",
      "data": 56862.6664136005,
      "description": "The warmup rate at which 16 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_32",
      "data": 54713.070701800156,
      "description": "The warmup rate at which 32 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "warmup_rate_64",
      "data": 63652.29004158193,
      "description": "The warmup rate at which 64 threads wrote data. The rate is mutations per second.",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "rate_1",
      "data": 62353.997561918346,
      "description": "The rate at which 1 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_2",
      "data": 69571.12526539278,
      "description": "The rate at which 2 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_4",
      "data": 68554.54218561015,
      "description": "The rate at which 4 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_8",
      "data": 63986.33104500382,
      "description": "The rate at which 8 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_16",
      "data": 64682.99302942447,
      "description": "The rate at which 16 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_32",
      "data": 69462.82004570898,
      "description": "The rate at which 32 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    },
    {
      "id": "rate_64",
      "data": 57982.028809201256,
      "description": "The rate at which 64 threads wrote data. The rate is mutations per second.",
      "purpose": "COMPARISON"
    }
  ],
  "parameters": [
    {
      "id": "num_mutations",
      "data": "2097152",
      "description": "The total number of mutations each test will write.  Each thread in a test will write num_mutations/num_threads_in_test mutations."
    },
    {
      "id": "num_flushes",
      "data": "1024",
      "description": "The number of times each thread will flush its batch writer.  The flushes are spread evenly between mutations."
    }
  ]
}

```

**Review by ctubbsii — APPROVED** [review]

**Pull request merged**
