### PR TITLE
Add units to performance test results

### LINKED ISSUE #23: Add units to performance test results
It would be helpful if the JSON contained units like 'milliseconds' or 'ms'

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #23 

* Added "units" parameter to report.java and result.java which adds units to the test output (JSON)
* Updated all usages of report.java and result.java to comply with new parameter

<details>
<summary>Current output, without units</summary>

```JSON
{
  "testClass": "org.apache.accumulo.testing.performance.tests.DurabilityWriteSpeedPT",
  "accumuloVersion": "2.1.0-SNAPSHOT",
  "startTime": "2021-09-22T12:38:32.950553Z",
  "finishTime": "2021-09-22T12:39:20.304474Z",
  "id": "durability",
  "description": "Compares writes speeds at different durability levels",
  "results": [
    {
      "id": "sync attempt 0",
      "data": 3984,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 1",
      "data": 3490,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 2",
      "data": 3726,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 3",
      "data": 3320,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 4",
      "data": 3696,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync Median",
      "data": 3696,
      "description": "Median time result for sync",
      "purpose": "COMPARISON"
    },
    {
      "id": "flush attempt 0",
      "data": 2527,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 1",
      "data": 896,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 2",
      "data": 986,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 3",
      "data": 1228,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 4",
      "data": 908,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush Median",
      "data": 986,
      "description": "Median time result for flush",
      "purpose": "COMPARISON"
    },
    {
      "id": "log attempt 0",
      "data": 2852,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 1",
      "data": 851,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 2",
      "data": 1090,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 3",
      "data": 1048,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 4",
      "data": 901,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log Median",
      "data": 1048,
      "description": "Median time result for log",
      "purpose": "COMPARISON"
    },
    {
      "id": "none attempt 0",
      "data": 2569,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 1",
      "data": 755,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 2",
      "data": 755,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 3",
      "data": 729,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 4",
      "data": 866,
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none Median",
      "data": 755,
      "description": "Median time result for none",
      "purpose": "COMPARISON"
    }
  ],
  "parameters": [
    {
      "id": "rows",
      "data": "100000",
      "description": "Number of random rows written."
    }
  ]
}
```

</details>

<details>
<summary>New output, with units</summary>

```JSON
{
  "testClass": "org.apache.accumulo.testing.performance.tests.DurabilityWriteSpeedPT",
  "accumuloVersion": "2.1.0-SNAPSHOT",
  "startTime": "2021-09-22T14:42:37.823125Z",
  "finishTime": "2021-09-22T14:43:24.283933Z",
  "id": "durability",
  "description": "Compares writes speeds at different durability levels",
  "results": [
    {
      "id": "sync attempt 0",
      "data": 3722,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 1",
      "data": 2925,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 2",
      "data": 3528,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 3",
      "data": 3712,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync attempt 4",
      "data": 3674,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "sync Median",
      "data": 3674,
      "units": "MILLISECONDS",
      "description": "Median time result for sync",
      "purpose": "COMPARISON"
    },
    {
      "id": "flush attempt 0",
      "data": 2903,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 1",
      "data": 897,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 2",
      "data": 993,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 3",
      "data": 1240,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush attempt 4",
      "data": 1021,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "flush Median",
      "data": 1021,
      "units": "MILLISECONDS",
      "description": "Median time result for flush",
      "purpose": "COMPARISON"
    },
    {
      "id": "log attempt 0",
      "data": 2843,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 1",
      "data": 888,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 2",
      "data": 831,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 3",
      "data": 863,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log attempt 4",
      "data": 856,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "log Median",
      "data": 863,
      "units": "MILLISECONDS",
      "description": "Median time result for log",
      "purpose": "COMPARISON"
    },
    {
      "id": "none attempt 0",
      "data": 2557,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 1",
      "data": 791,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 2",
      "data": 783,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 3",
      "data": 791,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none attempt 4",
      "data": 804,
      "units": "MILLISECONDS",
      "description": "Times for each attempt in ms",
      "purpose": "INFORMATIONAL"
    },
    {
      "id": "none Median",
      "data": 791,
      "units": "MILLISECONDS",
      "description": "Median time result for none",
      "purpose": "COMPARISON"
    }
  ],
  "parameters": [
    {
      "id": "rows",
      "data": "100000",
      "description": "Number of random rows written."
    }
  ]
}
```

</details>

### CODE REVIEW

**Comment by Manno15** [comment]
Slightly unrelated, have you run all these PTs to verify they still work as expected?

**Comment by DomGarguilo** [comment]
> Slightly unrelated, have you run all these PTs to verify they still work as expected?

Not all of the tests seem to be in running order, but all of the tests that I could get to run, yes.

**Review by ctubbsii — APPROVED** [review]

**Review by Manno15 — APPROVED** [review]
Changes look good. My only possible suggestion is some of the descriptions do not need the unit in them anymore with the unit being given separately. Not a huge deal

**Comment by DomGarguilo** [comment]
> Changes look good. My only possible suggestion is some of the descriptions do not need the unit in them anymore with the unit being given separately. Not a huge deal

I was considering that as well. I'll go ahead and update the descriptions.

**Comment by Manno15** [comment]
>I was considering that as well. I'll go ahead and update the descriptions.

It might not be worth the trouble. So up to you.

**Review by Manno15 — APPROVED** [review]
New changes look good.

**Pull request merged**
